In [13]:
import cv2, os, argparse
import numpy as np
from tqdm import tqdm

image_path = 'D:/cnnface/femaletrain/n00000068'
img_filenames = os.listdir(image_path)
m_list, s_list = [], []
for img_filename in tqdm(img_filenames):
    img = cv2.imread(image_path + '/' + img_filename)
    img = img 
    m, s = cv2.meanStdDev(img)
    m_list.append(m.reshape((3,)))
    s_list.append(s.reshape((3,)))
m_array = np.array(m_list)
s_array = np.array(s_list)
m = m_array.mean(axis=0, keepdims=True)[0][::-1]
s = s_array.mean(axis=0, keepdims=True)[0][::-1]



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 273/273 [00:00<00:00, 658.70it/s]


In [15]:
print(m,s)

[123.96625727  98.12430016  86.25645855] [70.6971554  63.42810227 60.49945422]


In [16]:
image_path = 'D:/cnnface/femaletrain/n00001586'
img_filenames = os.listdir(image_path)
m_list, s_list = [], []
for img_filename in tqdm(img_filenames):
    img = cv2.imread(image_path + '/' + img_filename)
    img = img 
    m, s = cv2.meanStdDev(img)
    m_list.append(m.reshape((3,)))
    s_list.append(s.reshape((3,)))
m_array = np.array(m_list)
s_array = np.array(s_list)
m2 = m_array.mean(axis=0, keepdims=True)[0][::-1]
s2 = s_array.mean(axis=0, keepdims=True)[0][::-1]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 243/243 [00:02<00:00, 87.10it/s]


In [17]:
print(m2,s2)

[125.68264899 100.13823264  88.79194902] [72.08836837 66.30032991 65.20277517]


In [18]:
m = np.array(m)
s = np.array(s)
m2 = np.array(m2)
s2 = np.array(s2)

In [24]:

print((m+m2)/2)
print((s+s2)/2)


[[128.37098011 115.59877193 109.92563012]
 [134.01342726 121.24121909 115.56807728]
 [145.33891014 132.56670196 126.89356015]]
[[77.8560656  74.96204637 74.413269  ]
 [76.45516721 73.56114798 73.01237061]
 [75.20822778 72.31420856 71.76543119]]


[[ 67.24330335  75.10495188  94.92515106]
 [ 64.61392218  66.86471322 113.99734535]
 [ 95.2668859  102.2174722  113.38582637]
 [ 55.29133327  68.52157387  89.93627687]
 [126.38605799 140.43667042 167.08533308]
 [ 50.43805926  62.9173792   83.56422748]
 [108.73961879 114.24336283 125.96895848]
 [ 72.9935739   81.00154474 100.80647553]
 [144.28729293 153.32745943 165.18631677]
 [ 69.00905556  76.32211111  94.65355556]
 [130.55478169 139.18920217 171.17503242]
 [ 70.50987919  78.68742238 100.89136797]
 [ 92.84367318 108.90627608 144.12871629]
 [ 64.61770376  65.29774096 127.08164642]
 [126.0012334  120.67352941 143.6955408 ]
 [ 61.38321777  72.27383532  99.91238353]
 [ 48.20353499  55.28999636  74.15123907]
 [ 70.09230205  70.15370235 135.8436217 ]
 [ 74.04436384  83.66775949 104.71107701]
 [ 81.53701387  99.12405922 129.97274355]
 [ 69.85277005  72.51739185 125.38198836]
 [132.6583304  142.1635846  166.0311436 ]
 [132.73959674 143.36994137 165.04568855]
 [111.9627287  123.99035673 151.14

 [131.05931122 142.34420554 164.99517128]]


In [12]:
import numpy as np
from PIL import Image

noise_r = np.zeros((224,224,1)) 
noise_g = np.zeros((224,224,1))
noise_b = np.ones((224,224,1))*255

noise_img = np.uint8(np.concatenate((noise_r,noise_g),axis=2))
noise_img = np.uint8(np.concatenate((noise_img,noise_b),axis=2))

noise_img = Image.fromarray(noise_img)
noise_img.save('F:/noise_blue.jpg')